#!/usr/bin/env python3
"""Usage:
nursery-build [options] [<stages>...]

Options:
--root=<path>  Path to the root
--name=<name>  Image name [default: rubus-base]
--start=<n>    Stage number to start from
"""

import glob
import os
import os.path
import subprocess

import docopt

CUSTOM_STAGE_PATH = "custom-stages"
SKIPPED_OFFICIAL_STAGES = (3, 4, 5)  # desktop, raspbian 4GB, raspbian offial


def prepare_source_tree(root, image_name, stages, start_at):
    for i in SKIPPED_OFFICIAL_STAGES:
        disable_stage(root, i, "disabled")
        disable_export(root, i)
    for i, nm in enumerate(stages, 6):
        link_stage(root, nm, i)
    for i in range(start_at):
        disable_stage(root, i, "skipped")
    with open("{}/config".format(root), "w+") as f:
        f.write("IMG_NAME={}\n".format(image_name))


def restore_source_tree(root, stages, start_at):
    for i in range(start_at):
        enable_stage(root, i)
    for i, nm in enumerate(stages, 6):
        unlink_stage(root, nm, i)
    for i in SKIPPED_OFFICIAL_STAGES:
        restore_export(root, i)
        enable_stage(root, i)


def disable_stage(root, number, reason):
    print("Disabling stage {} ({})".format(number, reason))
    path = "{root}/stage{number}/SKIP".format(root=root, number=number)
    if not os.path.exists(path):
        with open(path, "w+") as f:
            f.write("")


def enable_stage(root, number):
    print("Enabling stage {}".format(number))
    path = "{root}/stage{number}/SKIP".format(root=root, number=number)
    if os.path.exists(path):
        os.remove(path)


def disable_export(root, number):
    path_export = glob.glob("{root}/stage{number}/EXPORT_*".format(
        root=root, number=number))
    for f in path_export:
        print("Disabling export for stage {}: {}".format(
            number, os.path.basename(f).replace("EXPORT_", "")))
        os.rename(f, f.replace("EXPORT_", "_EXPORT_"))


def restore_export(root, number):
    path_export = glob.glob("{root}/stage{number}/_EXPORT_*".format(
        root=root, number=number))
    for f in path_export:
        print("Restoring export for stage {}: {}".format(
            number, os.path.basename(f).replace("_EXPORT_", "")))
        os.rename(f, f.replace("_EXPORT_", "EXPORT_"))


def link_stage(root, name, number):
    print("Linking custom stage '{}' as stage{}".format(name, number))
    path = "{root}/stage{number}".format(root=root, number=number)
    src = "{root}/stages/{name}".format(root=root, name=name)
    os.symlink(src, path)


def unlink_stage(root, name, number):
    print("Removing custom stage {} ({})".format(number, name))
    path = "{root}/stage{number}".format(root=root, number=number)
    if os.path.exists(path):
        os.remove(path)


def run(root, image_name, stages, start_at):
    try:
        prepare_source_tree(root, image_name, stages, start_at)
        subprocess.run("{}/build.sh".format(root), cwd=root, check=True)
        print("Success!")
    finally:
        print("Restoring source tree")
        restore_source_tree(root, stages, start_at)


if __name__ == "__main__":
    args = docopt.docopt(__doc__)
    root = args["--root"] or "."
    run(root, args['--name'], args['<stages>'], int(args['--start']))
